[2025-04-04T13:21:21.421+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T13:21:21.455+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: talend_job_execution.check_file_exists manual__2025-04-04T13:21:05.837613+00:00 [queued]>
[2025-04-04T13:21:21.471+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: talend_job_execution.check_file_exists manual__2025-04-04T13:21:05.837613+00:00 [queued]>
[2025-04-04T13:21:21.472+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-04T13:21:21.493+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): check_file_exists> on 2025-04-04 13:21:05.837613+00:00
[2025-04-04T13:21:21.504+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=561) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-04T13:21:21.506+0000] {standard_task_runner.py:72} INFO - Started process 562 to run task
[2025-04-04T13:21:21.504+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'talend_job_execution', 'check_file_exists', 'manual__2025-04-04T13:21:05.837613+00:00', '--job-id', '481', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpcdcsewzn']
[2025-04-04T13:21:21.507+0000] {standard_task_runner.py:105} INFO - Job 481: Subtask check_file_exists
[2025-04-04T13:21:21.529+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T13:21:21.570+0000] {task_command.py:467} INFO - Running <TaskInstance: talend_job_execution.check_file_exists manual__2025-04-04T13:21:05.837613+00:00 [running]> on host 98a2ddb84e26
[2025-04-04T13:21:21.681+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='talend_job_execution' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T13:21:05.837613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T13:21:05.837613+00:00'
[2025-04-04T13:21:21.682+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-04T13:21:21.698+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-04T13:21:21.699+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '\n        echo "Vérification du fichier de sortie..."\n        if [ -f /opt/***/talend_jobs/CorrigeAge/CorrigeAge/outdataset.xlsx ]; then\n            echo "Le fichier outdataset.xlsx existe."\n            # Vérifier la taille du fichier\n            ls -la /opt/***/talend_jobs/CorrigeAge/CorrigeAge/outdataset.xlsx\n        else\n            echo "Le fichier outdataset.xlsx n\'a pas été trouvé."\n            # Vérifier si le fichier est dans un autre répertoire\n            find /opt/***/talend_jobs -name "outdataset.xlsx" -type f\n        fi\n        ']
[2025-04-04T13:21:21.711+0000] {subprocess.py:99} INFO - Output:
[2025-04-04T13:21:21.713+0000] {subprocess.py:106} INFO - Vérification du fichier de sortie...
[2025-04-04T13:21:21.716+0000] {subprocess.py:106} INFO - Le fichier outdataset.xlsx existe.
[2025-04-04T13:21:21.728+0000] {subprocess.py:106} INFO - -rwxrwxrwx 1 root root 1160704 Apr  4 13:21 /opt/***/talend_jobs/CorrigeAge/CorrigeAge/outdataset.xlsx
[2025-04-04T13:21:21.729+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-04T13:21:21.758+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-04T13:21:21.759+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=talend_job_execution, task_id=check_file_exists, run_id=manual__2025-04-04T13:21:05.837613+00:00, execution_date=20250404T132105, start_date=20250404T132121, end_date=20250404T132121
[2025-04-04T13:21:21.844+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-04T13:21:21.880+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-04T13:21:21.884+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
